export DATABASE_URL := env('DATABASE_URL', "postgresql://postgres:postgres@localhost:5432/postgres")

format:
    cargo +nightly fmt --all
    cargo clippy
    cargo sqlx prepare

run-migrations:
    cargo sqlx migrate run

run-postgres:
    docker-compose kill || true
    docker rm --force trunk-registry-pg
    docker-compose up --build -d

stop-postgres:
    docker compose down

run:
    RUST_LOG=debug \
    RUST_BACKTRACE=full \
    GITHUB_TOKEN=$(gh auth token) \
    cargo run

test:
    cargo test -- --nocapture
