DATABASE_URL := "postgresql://postgres:postgres@localhost:5432/postgres"

format:
    cargo +nightly fmt --all
    DATABASE_URL=${DATABASE_URL} cargo clippy
    cargo sqlx prepare

run-migrations:
    DATABASE_URL={{DATABASE_URL}} cargo sqlx migrate run

run-postgres:
    docker-compose kill || true
    docker rm --force trunk-registry-pg
    docker-compose up --build -d

run:
    RUST_LOG=debug \
    DATABASE_URL={{DATABASE_URL}} \
    RUST_BACKTRACE=full \
    GITHUB_TOKEN=$(gh auth token) \
    cargo run
